<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class HomePageSettings extends Model
{
    use HasFactory;

    protected $fillable = [
        'is_slider_active',
        'is_about_section_active',
        'is_services_section_active',
        'is_projects_section_active',
        'is_news_section_active',
        'is_stats_section_active',
        'is_cta_section_active',
        'sliders',
        'about_title',
        'about_content',
        'about_image',
        'about_button_text',
        'about_button_link',
        'services_title',
        'services_description',
        'featured_services_count',
        'services_show_only_featured',
        'projects_title',
        'projects_description',
        'featured_projects_count',
        'projects_show_only_featured',
        'news_title',
        'news_description',
        'featured_news_count',
        'news_show_only_featured',
        'statistics',
        'stats_background_image',
        'cta_title',
        'cta_description',
        'cta_button_text',
        'cta_button_link',
        'cta_background_image',
        'is_video_section_active',
        'video_title',
        'video_description',
        'video_cover_image',
        'video_url',
        'meta_title',
        'meta_description',
        'meta_keywords',
        'og_image',
        'about_stat_1_number',
        'about_stat_1_text',
        'about_stat_2_number',
        'about_stat_2_text',
        'expertise_title',
        'expertise_subtitle',
        'expertise_description',
        'expertise_stat_1_number',
        'expertise_stat_1_text',
        'expertise_stat_2_number',
        'expertise_stat_2_text',
        'hero_title_1',
        'hero_description_1',
        'hero_image_1',
        'hero_title_2',
        'hero_description_2',
        'hero_image_2',
        'hero_title_3',
        'hero_description_3',
        'hero_image_3',
        'hero_slides',
        'about_image_1',
        'about_image_2',
        'about_images',
        'about_subtitle',
        'about_description',
        'facilities_title',
        'facilities_subtitle',
        'facilities_show',
        'projects_subtitle',
        'projects_show',
        'projects_map_show',
        'news_subtitle',
        'news_show',
        'news_count',
        'contact_title',
        'contact_subtitle',
        'contact_show',
    ];

    protected $casts = [
        'is_slider_active' => 'boolean',
        'is_about_section_active' => 'boolean',
        'is_services_section_active' => 'boolean',
        'is_projects_section_active' => 'boolean',
        'is_news_section_active' => 'boolean',
        'is_stats_section_active' => 'boolean',
        'is_cta_section_active' => 'boolean',
        'services_show_only_featured' => 'boolean',
        'projects_show_only_featured' => 'boolean',
        'news_show_only_featured' => 'boolean',
        'is_video_section_active' => 'boolean',
        'facilities_show' => 'boolean',
        'projects_show' => 'boolean',
        'projects_map_show' => 'boolean',
        'news_show' => 'boolean',
        'contact_show' => 'boolean',
        'hero_slides' => 'array',
        'about_images' => 'array',
        'sliders' => 'array',
        'statistics' => 'array',
    ];

    public static function getSettings()
    {
        return static::first() ?? new static();
    }
} 